name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # optional, silences Node.js 20 warning
  AZURE_WEBAPP_NAME: ecommerce-app-fury
  ACR_NAME: ecommerceacrp1
  IMAGE_NAME: ecommerce_app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set app settings (environment variables)
        run: |
          az webapp config appsettings set -g ecommerce-rg -n ${{ env.AZURE_WEBAPP_NAME }} \
            --settings MONGODB_URI=${{ secrets.MONGODB_URI }} \
                         JWT_SECRET=${{ secrets.JWT_SECRET }} \
                         NODE_ENV=production \
                         APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
